// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCax3QXgMJ6AuTP7GMHDIE4HVJTJfV42E',
    appId: '1:96223165965:web:e37f41ec1e323a296c9f44',
    messagingSenderId: '96223165965',
    projectId: 'login-page-flutter-app',
    authDomain: 'login-page-flutter-app.firebaseapp.com',
    storageBucket: 'login-page-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXSqcPAAUhuoXprUhh6-s8HJ6qZIw2AM',
    appId: '1:96223165965:android:f3df0e4f392fec3d6c9f44',
    messagingSenderId: '96223165965',
    projectId: 'login-page-flutter-app',
    storageBucket: 'login-page-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGVi6eAL9znv2FnNuRZAD7QtDZkqoE3oE',
    appId: '1:96223165965:ios:dbbd45e579d276626c9f44',
    messagingSenderId: '96223165965',
    projectId: 'login-page-flutter-app',
    storageBucket: 'login-page-flutter-app.appspot.com',
    iosClientId: '96223165965-7diifr7dg9ah53i3uhun3rd4qgh5eps9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
